In [60]:
#----------------------------IMPORTS----------------------------
import cv2
import numpy as np
import os
import random
import pickle
import tensorflow as tf
import keras 
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from tensorflow.keras.applications.resnet50 import ResNet50
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.models import Model
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from ultralytics import YOLO


In [61]:
model = YOLO("yolov8m.pt")  # load a pretrained YOLOv8n model

In [62]:
# use yolo model to predict an image and crop the image to the bounding box
results = model.predict(
    task="detect",
    source="bus.jpg",
    conf=0.5,
    save=True,
    save_txt=True,
    save_crop=True,
    line_thickness=1,
    hide_labels=False,
    hide_conf=False,
    classes=None,
    project = "./predictions",
    name = "test"
)
# The labels text output file has 5 columns: class, x1, y1, x2, y2

Ultralytics YOLOv8.0.41  Python-3.9.3 torch-1.13.1+cpu CPU
YOLOv8m summary (fused): 218 layers, 25886080 parameters, 0 gradients, 78.9 GFLOPs

image 1/1 D:\Work\CCE\Year 4 - Senior 2\Semester 1\Senior-2-Semester-1\GP\Graduation-Project\Scene Description Module\bus.jpg: 640x480 4 persons, 1 bus, 639.3ms
Speed: 2.0ms preprocess, 639.3ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 640)
Results saved to predictions\test
1 label saved to predictions\test\labels


In [52]:
classes = dict()
with open("coco.names.txt", "r") as f:
    lines = f.readlines()
    size = len(lines)
    for i in range(size):
        classes[i] = lines[i].strip()
print(classes)


{0: 'person', 1: 'bicycle', 2: 'car', 3: 'motorbike', 4: 'aeroplane', 5: 'bus', 6: 'train', 7: 'truck', 8: 'boat', 9: 'traffic light', 10: 'fire hydrant', 11: 'stop sign', 12: 'parking meter', 13: 'bench', 14: 'bird', 15: 'cat', 16: 'dog', 17: 'horse', 18: 'sheep', 19: 'cow', 20: 'elephant', 21: 'bear', 22: 'zebra', 23: 'giraffe', 24: 'backpack', 25: 'umbrella', 26: 'handbag', 27: 'tie', 28: 'suitcase', 29: 'frisbee', 30: 'skis', 31: 'snowboard', 32: 'sports ball', 33: 'kite', 34: 'baseball bat', 35: 'baseball glove', 36: 'skateboard', 37: 'surfboard', 38: 'tennis racket', 39: 'bottle', 40: 'wine glass', 41: 'cup', 42: 'fork', 43: 'knife', 44: 'spoon', 45: 'bowl', 46: 'banana', 47: 'apple', 48: 'sandwich', 49: 'orange', 50: 'broccoli', 51: 'carrot', 52: 'hot dog', 53: 'pizza', 54: 'donut', 55: 'cake', 56: 'chair', 57: 'sofa', 58: 'pottedplant', 59: 'bed', 60: 'diningtable', 61: 'toilet', 62: 'tvmonitor', 63: 'laptop', 64: 'mouse', 65: 'remote', 66: 'keyboard', 67: 'cell phone', 68: 'mi

In [109]:

boxes = ((results[0].boxes)).boxes.numpy()
bounding_boxes=[]
for box in boxes:
    x1,y1,x2,y2,conf,category = box
    bounding_boxes.append([x1,y1,x2,y2])

bounding_boxes= np.array(bounding_boxes)
print(bounding_boxes)


[[          3         229         804         741]
 [         50         400         247         905]
 [        668         395         810         881]
 [        222         411         344         861]
 [          0         550          78         872]]
